Feature/selection change tracking
thmq/NewUi pull request #19
Opened 2017-04-26 14:54 UTC by matthee

2017-04-28 11:27 UTC, thmq requested changes

2017-04-28 11:27 UTC, thmq commented on .idea/misc.xml
> -  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" assert-keyword="true" jdk-15="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
please do not change .idea files.

2017-04-28 11:27 UTC, thmq commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/NewUi.iml" filepath="$PROJECT_DIR$/NewUi.iml" />
please don't. 🌵

2017-05-03 06:57 UTC, matthee commented
ping @thmq

2017-05-03 13:19 UTC, thmq approved these changes

2017-05-03 13:19 UTC, merged